const data = [
  {
    kind: "Listing",
    data: {
      after: null,
      dist: 1,
      modhash: "",
      geo_filter: "",
      children: [
        {
          kind: "t3",
          data: {
            approved_at_utc: null,
            subreddit: "Home",
            selftext: "",
            author_fullname: "t2_pc3go",
            saved: false,
            mod_reason_title: null,
            gilded: 0,
            clicked: false,
            title: "Prime crawl space - How would you convert it?",
            link_flair_richtext: [],
            subreddit_name_prefixed: "r/Home",
            hidden: false,
            pwls: 6,
            link_flair_css_class: null,
            downs: 0,
            thumbnail_height: null,
            top_awarded_type: null,
            parent_whitelist_status: "all_ads",
            hide_score: false,
            name: "t3_vly3zz",
            quarantine: false,
            link_flair_text_color: "dark",
            upvote_ratio: 1.0,
            author_flair_background_color: null,
            subreddit_type: "public",
            ups: 1,
            total_awards_received: 0,
            media_embed: {},
            thumbnail_width: null,
            author_flair_template_id: null,
            is_original_content: false,
            user_reports: [],
            secure_media: null,
            is_reddit_media_domain: false,
            is_meta: false,
            category: null,
            secure_media_embed: {},
            link_flair_text: null,
            can_mod_post: false,
            score: 1,
            approved_by: null,
            is_created_from_ads_ui: false,
            author_premium: false,
            thumbnail: "default",
            edited: false,
            author_flair_css_class: null,
            author_flair_richtext: [],
            gildings: {},
            post_hint: "link",
            content_categories: null,
            is_self: false,
            mod_note: null,
            crosspost_parent_list: [
              {
                approved_at_utc: null,
                subreddit: "HomeImprovement",
                selftext:
                  "Our townhome had foundation work done a few years before we purchased it. It’s in great shape now, and the work left our massive crawl space (~13’ x 25’) mostly dugout (as compared to our attached neighbor’s that actually CRAWL space). Ours is more stand and jump and do summersaults space. \n\nIt’s accessible off our garage with 3/4 of it on the other side of our garage and 1/4 behind a wall to my office/back door mud room (that’s where the return vent is in the photos.)\n\nI’m comfortable getting my brothers over to breakup a few larger rocks and level the ground. \n\nAside from that, I’m curious what you fine home improvers would do with this space if it were yours?!?!\n\nAt the very least, I plan on using it for storage, so leveling, vapor layer + horse stall mats, replacing insulation, put up a ceiling. Right now our garage is our gym, so I could also move our gym into this space and have our garage back.\n\nAt the most, I’ve considered walling it up and adding livable sq fts w/ bathroom, bedroom, and storage.\n\nhttps://imgur.com/a/R4P2kx9",
                user_reports: [],
                saved: false,
                mod_reason_title: null,
                gilded: 0,
                clicked: false,
                title: "Prime crawl space - How would you convert it?",
                link_flair_richtext: [],
                subreddit_name_prefixed: "r/HomeImprovement",
                hidden: false,
                pwls: 6,
                link_flair_css_class: null,
                downs: 0,
                thumbnail_height: null,
                top_awarded_type: null,
                parent_whitelist_status: "all_ads",
                hide_score: false,
                name: "t3_vlkye4",
                quarantine: false,
                link_flair_text_color: "dark",
                upvote_ratio: 0.76,
                author_flair_background_color: null,
                subreddit_type: "public",
                ups: 2,
                total_awards_received: 0,
                media_embed: {},
                thumbnail_width: null,
                author_flair_template_id: null,
                is_original_content: false,
                author_fullname: "t2_pc3go",
                secure_media: null,
                is_reddit_media_domain: false,
                is_meta: false,
                category: null,
                secure_media_embed: {},
                link_flair_text: null,
                can_mod_post: false,
                score: 2,
                approved_by: null,
                is_created_from_ads_ui: false,
                author_premium: false,
                thumbnail: "self",
                edited: false,
                author_flair_css_class: null,
                author_flair_richtext: [],
                gildings: {},
                post_hint: "self",
                content_categories: null,
                is_self: true,
                mod_note: null,
                created: 1656297486.0,
                link_flair_type: "text",
                wls: 6,
                removed_by_category: null,
                banned_by: null,
                author_flair_type: "text",
                domain: "self.HomeImprovement",
                allow_live_comments: false,
                selftext_html:
                  '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;Our townhome had foundation work done a few years before we purchased it. It’s in great shape now, and the work left our massive crawl space (~13’ x 25’) mostly dugout (as compared to our attached neighbor’s that actually CRAWL space). Ours is more stand and jump and do summersaults space. &lt;/p&gt;\n\n&lt;p&gt;It’s accessible off our garage with 3/4 of it on the other side of our garage and 1/4 behind a wall to my office/back door mud room (that’s where the return vent is in the photos.)&lt;/p&gt;\n\n&lt;p&gt;I’m comfortable getting my brothers over to breakup a few larger rocks and level the ground. &lt;/p&gt;\n\n&lt;p&gt;Aside from that, I’m curious what you fine home improvers would do with this space if it were yours?!?!&lt;/p&gt;\n\n&lt;p&gt;At the very least, I plan on using it for storage, so leveling, vapor layer + horse stall mats, replacing insulation, put up a ceiling. Right now our garage is our gym, so I could also move our gym into this space and have our garage back.&lt;/p&gt;\n\n&lt;p&gt;At the most, I’ve considered walling it up and adding livable sq fts w/ bathroom, bedroom, and storage.&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://imgur.com/a/R4P2kx9"&gt;https://imgur.com/a/R4P2kx9&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
                likes: null,
                suggested_sort: null,
                banned_at_utc: null,
                view_count: null,
                archived: false,
                no_follow: true,
                is_crosspostable: false,
                pinned: false,
                over_18: false,
                preview: {
                  images: [
                    {
                      source: {
                        url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?auto=webp&amp;s=a3c5dde3efd35975afe93d427986850389ad0207",
                        width: 2048,
                        height: 1536,
                      },
                      resolutions: [
                        {
                          url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=f676d4c1d1ca51ce35706aba63f455fa8799c1c5",
                          width: 108,
                          height: 81,
                        },
                        {
                          url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=f54951907421397239342e8792cd7852493be1e0",
                          width: 216,
                          height: 162,
                        },
                        {
                          url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=3e15dafc728a66044b09a0995c7105e2910d349b",
                          width: 320,
                          height: 240,
                        },
                        {
                          url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=b2ac6b863056e0fdc343c292de34c3ccf328fce3",
                          width: 640,
                          height: 480,
                        },
                        {
                          url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=6ac95566b3492a996ed0d01c43c2a500177b9ca3",
                          width: 960,
                          height: 720,
                        },
                        {
                          url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=c2c68b49c0f7cc2f964e9c8fa604c3bc7daadf3f",
                          width: 1080,
                          height: 810,
                        },
                      ],
                      variants: {},
                      id: "Y5J_eF1yjTrrrgqrk57XoKjooos4T4XCtAFQoyCEEsw",
                    },
                  ],
                  enabled: false,
                },
                all_awardings: [],
                awarders: [],
                media_only: false,
                can_gild: false,
                spoiler: false,
                locked: false,
                author_flair_text: null,
                treatment_tags: [],
                visited: false,
                removed_by: null,
                num_reports: null,
                distinguished: null,
                subreddit_id: "t5_2ql97",
                author_is_blocked: false,
                mod_reason_by: null,
                removal_reason: null,
                link_flair_background_color: "",
                id: "vlkye4",
                is_robot_indexable: true,
                report_reasons: null,
                author: "jguinn",
                discussion_type: null,
                num_comments: 5,
                send_replies: true,
                media: null,
                contest_mode: false,
                author_patreon_flair: false,
                author_flair_text_color: null,
                permalink:
                  "/r/HomeImprovement/comments/vlkye4/prime_crawl_space_how_would_you_convert_it/",
                whitelist_status: "all_ads",
                stickied: false,
                url: "https://www.reddit.com/r/HomeImprovement/comments/vlkye4/prime_crawl_space_how_would_you_convert_it/",
                subreddit_subscribers: 3087670,
                created_utc: 1656297486.0,
                num_crossposts: 1,
                mod_reports: [],
                is_video: false,
              },
            ],
            created: 1656343678.0,
            link_flair_type: "text",
            wls: 6,
            removed_by_category: null,
            banned_by: null,
            author_flair_type: "text",
            domain: "self.HomeImprovement",
            allow_live_comments: false,
            selftext_html: null,
            likes: null,
            suggested_sort: null,
            banned_at_utc: null,
            url_overridden_by_dest:
              "/r/HomeImprovement/comments/vlkye4/prime_crawl_space_how_would_you_convert_it/",
            view_count: null,
            archived: false,
            no_follow: true,
            is_crosspostable: false,
            pinned: false,
            over_18: false,
            preview: {
              images: [
                {
                  source: {
                    url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?auto=webp&amp;s=a3c5dde3efd35975afe93d427986850389ad0207",
                    width: 2048,
                    height: 1536,
                  },
                  resolutions: [
                    {
                      url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=f676d4c1d1ca51ce35706aba63f455fa8799c1c5",
                      width: 108,
                      height: 81,
                    },
                    {
                      url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=f54951907421397239342e8792cd7852493be1e0",
                      width: 216,
                      height: 162,
                    },
                    {
                      url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=3e15dafc728a66044b09a0995c7105e2910d349b",
                      width: 320,
                      height: 240,
                    },
                    {
                      url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=b2ac6b863056e0fdc343c292de34c3ccf328fce3",
                      width: 640,
                      height: 480,
                    },
                    {
                      url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=6ac95566b3492a996ed0d01c43c2a500177b9ca3",
                      width: 960,
                      height: 720,
                    },
                    {
                      url: "https://external-preview.redd.it/sLpE_TikF_2-QD3jyOtUERcrfLcyK3iyBeXo2p-kyX0.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=c2c68b49c0f7cc2f964e9c8fa604c3bc7daadf3f",
                      width: 1080,
                      height: 810,
                    },
                  ],
                  variants: {},
                  id: "Y5J_eF1yjTrrrgqrk57XoKjooos4T4XCtAFQoyCEEsw",
                },
              ],
              enabled: false,
            },
            all_awardings: [],
            awarders: [],
            media_only: false,
            can_gild: false,
            spoiler: false,
            locked: false,
            author_flair_text: null,
            treatment_tags: [],
            visited: false,
            removed_by: null,
            num_reports: null,
            distinguished: null,
            subreddit_id: "t5_2qs0k",
            author_is_blocked: false,
            mod_reason_by: null,
            removal_reason: null,
            link_flair_background_color: "",
            id: "vly3zz",
            is_robot_indexable: true,
            num_duplicates: 0,
            report_reasons: null,
            author: "jguinn",
            discussion_type: null,
            num_comments: 0,
            send_replies: true,
            media: null,
            contest_mode: false,
            author_patreon_flair: false,
            crosspost_parent: "t3_vlkye4",
            author_flair_text_color: null,
            permalink:
              "/r/Home/comments/vly3zz/prime_crawl_space_how_would_you_convert_it/",
            whitelist_status: "all_ads",
            stickied: false,
            url: "/r/HomeImprovement/comments/vlkye4/prime_crawl_space_how_would_you_convert_it/",
            subreddit_subscribers: 67270,
            created_utc: 1656343678.0,
            num_crossposts: 0,
            mod_reports: [],
            is_video: false,
          },
        },
      ],
      before: null,
    },
  },
  {
    kind: "Listing",
    data: {
      after: null,
      dist: null,
      modhash: "",
      geo_filter: "",
      children: [],
      before: null,
    },
  },
];

console.log(data[1].children);
